# Datasource
spring.datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:

spring.jpa:
    hibernate.ddl-auto: create
    show-sql: true

#spring.devtools.livereload.enabled: true


